// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1096mj5CyUV8OUx-E8YuQptvjqDd8gfE',
    appId: '1:642935751205:android:6fa92cccb9a7c3d0acb5cc',
    messagingSenderId: '642935751205',
    projectId: 'batch-14-ca67e',
    storageBucket: 'batch-14-ca67e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ6EKbnYEzM54sIOUB6vohV1qOkBzV0UY',
    appId: '1:642935751205:ios:ba648e10ffcccd27acb5cc',
    messagingSenderId: '642935751205',
    projectId: 'batch-14-ca67e',
    storageBucket: 'batch-14-ca67e.firebasestorage.app',
    androidClientId: '642935751205-cqlnvba69198i6813qinrrbggatru9sl.apps.googleusercontent.com',
    iosClientId: '642935751205-g6jvojv5tr5i7ehr1tso4bpclb7cd079.apps.googleusercontent.com',
    iosBundleId: 'com.example.craftyBay',
  );
}
